version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::408415622013:user/aws-sam-cli-managed-dev-env-pipeline-PipelineUser-ZN410EDRPA89"
permissions_provider = "AWS IAM"

[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::408415622013:role/aws-sam-cli-managed-dev-env-PipelineExecutionRole-LFOCKZKDQNSM"
cloudformation_execution_role = "arn:aws:iam::408415622013:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionR-D0COMA2TRVHX"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-s3kt16mht02z"
image_repository = ""
region = "us-east-1"

[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::408415622013:role/aws-sam-cli-managed-prod-env-PipelineExecutionRole-1QMIO8MJNN80F"
cloudformation_execution_role = "arn:aws:iam::408415622013:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-YO3QQVU4EOZ0"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-df0crqcfka2t"
image_repository = ""
region = "us-east-1"
